#
# Vivado (TM) v2016.2 (64-bit)
#
# Nicola3ZRadio_BuildVivado.tcl: Tcl script for re-creating project 'N3Z_TD_FIFO'
#
# Generated by Vivado on Sun Mar 05 21:27:56 GMT 2017
# IP Build 1577682 on Fri Jun  3 12:00:54 MDT 2016
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (Nicola3ZRadio_BuildVivado.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    <none>
#
# 3. The following remote source files that were added to the original project:-
#
#    "/home/gnaylor/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/N3Z_TD_FIFO/N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/PS_PL.bd"
#    "/home/gnaylor/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/N3Z_TD_FIFO/N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/hdl/PS_PL_wrapper.v"
#    "/home/gnaylor/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/N3Z_TD_FIFO/N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_3_i0_vivado.coe"
#    "/home/gnaylor/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/N3Z_TD_FIFO/N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_3_i1_vivado.coe"
#    "/home/gnaylor/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/N3Z_TD_FIFO/N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_3_i2_vivado.coe"
#    "/home/gnaylor/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/N3Z_TD_FIFO/N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_3_i3_vivado.coe"
#    "/home/gnaylor/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/N3Z_TD_FIFO/N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_3_i4_vivado.coe"
#    "/home/gnaylor/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/N3Z_TD_FIFO/N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_3_i5_vivado.coe"
#    "/home/gnaylor/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/N3Z_TD_FIFO/N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_dist_mem_gen_v8_0_i0_vivado.coe"
#    "/home/gnaylor/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/N3Z_TD_FIFO/N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_dist_mem_gen_v8_0_i1_vivado.coe"
#    "/home/gnaylor/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/N3Z_TD_FIFO/N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_dist_mem_gen_v8_0_i2_vivado.coe"
#    "/home/gnaylor/Dropbox/N3workingG/TE0722Rebuild/N3SysGen/UserPico.coe"
#    "/home/gnaylor/Dropbox/N3workingG/TE0722Rebuild/N3SysGen/DSPpico.coe"
#    "/home/gnaylor/Dropbox/N3workingG/TE0722Rebuild/N3SysGen/KeyPadPico.coe"
#    "/home/gnaylor/Dropbox/N3workingG/TE0722Rebuild/N3SysGen/ToneDetectpico.coe"
#    "/home/gnaylor/Dropbox/N3SysGen/DSPpico.coe"
#    "/home/gnaylor/Dropbox/N3SysGen/KeyPadPico.coe"
#    "/home/gnaylor/Dropbox/N3SysGen/ToneDetectpico.coe"
#    "/home/gnaylor/Dropbox/N3SysGen/UserPico.coe"
#    "/home/gnaylor/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/N3Z_TD_FIFO/N3Z_TD_FIFO.srcs/constrs_1/imports/VivadoProject/n3_te0722a5_clock.xdc"
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

variable script_file
set script_file "Nicola3ZRadio_BuildVivado.tcl"

# Help information for this script
proc help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < [llength $::argc]} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir" { incr i; set origin_dir [lindex $::argv $i] }
      "--help"       { help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/../Dropbox/N3workingG/TE0722Rebuild/N3Vivado/N3Z_TD_FIFO"]"

# Create project
create_project N3Z_TD_FIFO ./N3Z_TD_FIFO -part xc7z010clg225-1

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Reconstruct message rules
# None

# Set project properties
set obj [get_projects N3Z_TD_FIFO]
set_property "compxlib.activehdl_compiled_library_dir" "/home/graham/home/graham/home/graham/home/graham/home/graham/home/graham/home/graham/home/graham/Users/gnaylor.CCFEPC/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722TD/TE0722TD.cache/compile_simlib/activehdl" $obj
set_property "compxlib.ies_compiled_library_dir" "/home/graham/home/graham/home/graham/home/graham/home/graham/home/graham/home/graham/home/graham/Users/gnaylor.CCFEPC/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722TD/TE0722TD.cache/compile_simlib/ies" $obj
set_property "compxlib.modelsim_compiled_library_dir" "/home/graham/home/graham/home/graham/home/graham/home/graham/home/graham/home/graham/home/graham/Users/gnaylor.CCFEPC/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722TD/TE0722TD.cache/compile_simlib/modelsim" $obj
set_property "compxlib.questa_compiled_library_dir" "/home/graham/home/graham/home/graham/home/graham/home/graham/home/graham/home/graham/home/graham/Users/gnaylor.CCFEPC/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722TD/TE0722TD.cache/compile_simlib/questa" $obj
set_property "compxlib.riviera_compiled_library_dir" "/home/graham/home/graham/home/graham/home/graham/home/graham/home/graham/home/graham/home/graham/Users/gnaylor.CCFEPC/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722TD/TE0722TD.cache/compile_simlib/riviera" $obj
set_property "compxlib.vcs_compiled_library_dir" "/home/graham/home/graham/home/graham/home/graham/home/graham/home/graham/home/graham/home/graham/Users/gnaylor.CCFEPC/Dropbox/N3workingG/TE0722Rebuild/N3Vivado/TE0722TD/TE0722TD.cache/compile_simlib/vcs" $obj
set_property "default_lib" "xil_defaultlib" $obj
set_property "generate_ip_upgrade_log" "0" $obj
set_property "part" "xc7z010clg225-1" $obj
set_property "sim.ip.auto_export_scripts" "1" $obj
set_property "simulator_language" "Mixed" $obj
set_property "source_mgmt_mode" "None" $obj
set_property "xpm_libraries" "XPM_CDC XPM_MEMORY" $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set IP repository paths
set obj [get_filesets sources_1]
set_property "ip_repo_paths" "[file normalize "$origin_dir/../Dropbox/cores"] [file normalize "$origin_dir/../Dropbox/SysgenOutput/TE0722/ToneDetect2"]" $obj

# Rebuild user ip_repo's index before adding any source files
update_ip_catalog -rebuild

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/../Dropbox/N3workingG/TE0722Rebuild/N3Vivado/N3Z_TD_FIFO/N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/PS_PL.bd"]"\
 "[file normalize "$origin_dir/../Dropbox/N3workingG/TE0722Rebuild/N3Vivado/N3Z_TD_FIFO/N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/hdl/PS_PL_wrapper.v"]"\
 "[file normalize "$origin_dir/../Dropbox/N3workingG/TE0722Rebuild/N3Vivado/N3Z_TD_FIFO/N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_3_i0_vivado.coe"]"\
 "[file normalize "$origin_dir/../Dropbox/N3workingG/TE0722Rebuild/N3Vivado/N3Z_TD_FIFO/N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_3_i1_vivado.coe"]"\
 "[file normalize "$origin_dir/../Dropbox/N3workingG/TE0722Rebuild/N3Vivado/N3Z_TD_FIFO/N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_3_i2_vivado.coe"]"\
 "[file normalize "$origin_dir/../Dropbox/N3workingG/TE0722Rebuild/N3Vivado/N3Z_TD_FIFO/N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_3_i3_vivado.coe"]"\
 "[file normalize "$origin_dir/../Dropbox/N3workingG/TE0722Rebuild/N3Vivado/N3Z_TD_FIFO/N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_3_i4_vivado.coe"]"\
 "[file normalize "$origin_dir/../Dropbox/N3workingG/TE0722Rebuild/N3Vivado/N3Z_TD_FIFO/N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_3_i5_vivado.coe"]"\
 "[file normalize "$origin_dir/../Dropbox/N3workingG/TE0722Rebuild/N3Vivado/N3Z_TD_FIFO/N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_dist_mem_gen_v8_0_i0_vivado.coe"]"\
 "[file normalize "$origin_dir/../Dropbox/N3workingG/TE0722Rebuild/N3Vivado/N3Z_TD_FIFO/N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_dist_mem_gen_v8_0_i1_vivado.coe"]"\
 "[file normalize "$origin_dir/../Dropbox/N3workingG/TE0722Rebuild/N3Vivado/N3Z_TD_FIFO/N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_dist_mem_gen_v8_0_i2_vivado.coe"]"\
 "[file normalize "$origin_dir/../Dropbox/N3workingG/TE0722Rebuild/N3SysGen/UserPico.coe"]"\
 "[file normalize "$origin_dir/../Dropbox/N3workingG/TE0722Rebuild/N3SysGen/DSPpico.coe"]"\
 "[file normalize "$origin_dir/../Dropbox/N3workingG/TE0722Rebuild/N3SysGen/KeyPadPico.coe"]"\
 "[file normalize "$origin_dir/../Dropbox/N3workingG/TE0722Rebuild/N3SysGen/ToneDetectpico.coe"]"\
 "[file normalize "$origin_dir/../Dropbox/N3SysGen/DSPpico.coe"]"\
 "[file normalize "$origin_dir/../Dropbox/N3SysGen/KeyPadPico.coe"]"\
 "[file normalize "$origin_dir/../Dropbox/N3SysGen/ToneDetectpico.coe"]"\
 "[file normalize "$origin_dir/../Dropbox/N3SysGen/UserPico.coe"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/../Dropbox/N3workingG/TE0722Rebuild/N3Vivado/N3Z_TD_FIFO/N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/PS_PL.bd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
if { ![get_property "is_locked" $file_obj] } {
  set_property "generate_synth_checkpoint" "0" $file_obj
}

set file "$origin_dir/../Dropbox/N3workingG/TE0722Rebuild/N3Vivado/N3Z_TD_FIFO/N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_3_i0_vivado.coe"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "used_in" "" $file_obj
set_property "used_in_simulation" "0" $file_obj
set_property "used_in_synthesis" "0" $file_obj

set file "$origin_dir/../Dropbox/N3workingG/TE0722Rebuild/N3Vivado/N3Z_TD_FIFO/N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_3_i1_vivado.coe"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "used_in" "" $file_obj
set_property "used_in_simulation" "0" $file_obj
set_property "used_in_synthesis" "0" $file_obj

set file "$origin_dir/../Dropbox/N3workingG/TE0722Rebuild/N3Vivado/N3Z_TD_FIFO/N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_3_i2_vivado.coe"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "used_in" "" $file_obj
set_property "used_in_simulation" "0" $file_obj
set_property "used_in_synthesis" "0" $file_obj

set file "$origin_dir/../Dropbox/N3workingG/TE0722Rebuild/N3Vivado/N3Z_TD_FIFO/N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_3_i3_vivado.coe"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "used_in" "" $file_obj
set_property "used_in_simulation" "0" $file_obj
set_property "used_in_synthesis" "0" $file_obj

set file "$origin_dir/../Dropbox/N3workingG/TE0722Rebuild/N3Vivado/N3Z_TD_FIFO/N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_3_i4_vivado.coe"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "used_in" "" $file_obj
set_property "used_in_simulation" "0" $file_obj
set_property "used_in_synthesis" "0" $file_obj

set file "$origin_dir/../Dropbox/N3workingG/TE0722Rebuild/N3Vivado/N3Z_TD_FIFO/N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_blk_mem_gen_v8_3_i5_vivado.coe"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "used_in" "" $file_obj
set_property "used_in_simulation" "0" $file_obj
set_property "used_in_synthesis" "0" $file_obj

set file "$origin_dir/../Dropbox/N3workingG/TE0722Rebuild/N3Vivado/N3Z_TD_FIFO/N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_dist_mem_gen_v8_0_i0_vivado.coe"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "used_in" "" $file_obj
set_property "used_in_simulation" "0" $file_obj
set_property "used_in_synthesis" "0" $file_obj

set file "$origin_dir/../Dropbox/N3workingG/TE0722Rebuild/N3Vivado/N3Z_TD_FIFO/N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_dist_mem_gen_v8_0_i1_vivado.coe"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "used_in" "" $file_obj
set_property "used_in_simulation" "0" $file_obj
set_property "used_in_synthesis" "0" $file_obj

set file "$origin_dir/../Dropbox/N3workingG/TE0722Rebuild/N3Vivado/N3Z_TD_FIFO/N3Z_TD_FIFO.srcs/sources_1/bd/PS_PL/ip/PS_PL_n3z_tonetest_0_0/n3z_tonetest_dist_mem_gen_v8_0_i2_vivado.coe"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "used_in" "" $file_obj
set_property "used_in_simulation" "0" $file_obj
set_property "used_in_synthesis" "0" $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property "top" "PS_PL_wrapper" $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/../Dropbox/N3workingG/TE0722Rebuild/N3Vivado/N3Z_TD_FIFO/N3Z_TD_FIFO.srcs/constrs_1/imports/VivadoProject/n3_te0722a5_clock.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "$origin_dir/../Dropbox/N3workingG/TE0722Rebuild/N3Vivado/N3Z_TD_FIFO/N3Z_TD_FIFO.srcs/constrs_1/imports/VivadoProject/n3_te0722a5_clock.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property "target_constrs_file" "$orig_proj_dir/N3Z_TD_FIFO.srcs/constrs_1/imports/VivadoProject/n3_te0722a5_clock.xdc" $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Empty (no sources present)

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property "top" "PS_PL_wrapper" $obj
set_property "transport_int_delay" "0" $obj
set_property "transport_path_delay" "0" $obj
set_property "xelab.nosort" "1" $obj
set_property "xelab.unifast" "" $obj

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
  create_run -name synth_1 -part xc7z010clg225-1 -flow {Vivado Synthesis 2014} -strategy "Vivado Synthesis Defaults" -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2014" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property "part" "xc7z010clg225-1" $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
  create_run -name impl_1 -part xc7z010clg225-1 -flow {Vivado Implementation 2014} -strategy "Vivado Implementation Defaults" -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2014" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property "part" "xc7z010clg225-1" $obj
set_property "steps.write_bitstream.args.readback_file" "0" $obj
set_property "steps.write_bitstream.args.verbose" "0" $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:N3Z_TD_FIFO"
